CREATE TABLE FIFA_PLAYERS (
    SOFIFA_ID INTEGER,
    SHORT_NAME VARCHAR(50),
    LONG_NAME VARCHAR(98),
    PLAYER_POSITIONS VARCHAR(50),
    OVERALL INTEGER,
    POTENTIAL INTEGER,
    VALUE_EUR INTEGER,
    WAGE_EUR INTEGER,
    AGE INTEGER,
    DOB VARCHAR(50),
    HEIGHT_CM INTEGER,
    WEIGHT_KG INTEGER,
    CLUB_TEAM_ID INTEGER,
    CLUB_NAME VARCHAR(62),
    LEAGUE_NAME VARCHAR(60),
    LEAGUE_LEVEL INTEGER,
    CLUB_POSITION VARCHAR(50),
    CLUB_JERSEY_NUMBER INTEGER,
    CLUB_LOANED_FROM VARCHAR(52),
    DATE_CLUB_JOINED VARCHAR(50),
    CLUB_CONTRACT_VALID_UNTIL INTEGER,
    NATIONALITY_ID INTEGER,
    NATIONALITY_NAME VARCHAR(50),
    NATION_TEAM_ID INTEGER,
    NATION_POSITION VARCHAR(50),
    NATION_JERSEY_NUMBER INTEGER,
    PREFERRED_FOOT VARCHAR(50),
    WEAK_FOOT INTEGER,
    SKILL_MOVES INTEGER,
    INTERNATIONAL_REPUTATION INTEGER,
    WORK_RATE VARCHAR(50),
    BODY_TYPE VARCHAR(50),
    REAL_FACE VARCHAR(50),
    PLAYER_TAGS VARCHAR(206),
    PLAYER_TRAITS VARCHAR(226),
    PACE INTEGER,
    SHOOTING INTEGER,
    PASSING INTEGER,
    DRIBBLING INTEGER,
    DEFENDING INTEGER,
    PHYSIC INTEGER,
    ATTACKING_CROSSING INTEGER,
    ATTACKING_FINISHING INTEGER,
    ATTACKING_HEADING_ACCURACY INTEGER,
    ATTACKING_SHORT_PASSING INTEGER,
    ATTACKING_VOLLEYS INTEGER,
    SKILL_DRIBBLING INTEGER,
    SKILL_CURVE INTEGER,
    SKILL_FK_ACCURACY INTEGER,
    SKILL_LONG_PASSING INTEGER,
    SKILL_BALL_CONTROL INTEGER,
    MOVEMENT_ACCELERATION INTEGER,
    MOVEMENT_SPRINT_SPEED INTEGER,
    MOVEMENT_AGILITY INTEGER,
    MOVEMENT_REACTIONS INTEGER,
    MOVEMENT_BALANCE INTEGER,
    POWER_SHOT_POWER INTEGER,
    POWER_JUMPING INTEGER,
    POWER_STAMINA INTEGER,
    POWER_STRENGTH INTEGER,
    POWER_LONG_SHOTS INTEGER,
    MENTALITY_AGGRESSION INTEGER,
    MENTALITY_INTERCEPTIONS INTEGER,
    MENTALITY_POSITIONING INTEGER,
    MENTALITY_VISION INTEGER,
    MENTALITY_PENALTIES INTEGER,
    MENTALITY_COMPOSURE INTEGER,
    DEFENDING_MARKING_AWARENESS INTEGER,
    DEFENDING_STANDING_TACKLE INTEGER,
    DEFENDING_SLIDING_TACKLE INTEGER,
    GOALKEEPING_DIVING INTEGER,
    GOALKEEPING_HANDLING INTEGER,
    GOALKEEPING_KICKING INTEGER,
    GOALKEEPING_POSITIONING INTEGER,
    GOALKEEPING_REFLEXES INTEGER,
    GOALKEEPING_SPEED INTEGER,
    LS VARCHAR(50),
    ST VARCHAR(50),
    RS VARCHAR(50),
    LW VARCHAR(50),
    LF VARCHAR(50),
    CF VARCHAR(50),
    RF VARCHAR(50),
    RW VARCHAR(50),
    LAM VARCHAR(50),
    CAM VARCHAR(50),
    RAM VARCHAR(50),
    LM VARCHAR(50),
    LCM VARCHAR(50),
    CM VARCHAR(50),
    RCM VARCHAR(50),
    RM VARCHAR(50),
    LWB VARCHAR(50),
    LDM VARCHAR(50),
    CDM VARCHAR(50),
    RDM VARCHAR(50),
    RWB VARCHAR(50),
    LB VARCHAR(50),
    LCB VARCHAR(50),
    CB VARCHAR(50),
    RCB VARCHAR(50),
    RB VARCHAR(50),
    GK VARCHAR(50),
    FIFA_EDITION INTEGER
);

SELECT COUNT(*) FROM FIFA_PLAYERS;

SELECT SHORT_NAME, LONG_NAME, CLUB_NAME, NATIONALITY_NAME, OVERALL
FROM FIFA_PLAYERS
WHERE FIFA_EDITION = 22
ORDER BY OVERALL DESC
FETCH FIRST 10 ROWS ONLY;

SELECT NATIONALITY_NAME, COUNT(*) AS PLAYER_COUNT
FROM FIFA_PLAYERS
WHERE FIFA_EDITION = 22
AND OVERALL >= 85
GROUP BY NATIONALITY_NAME
ORDER BY PLAYER_COUNT DESC
FETCH FIRST 10 ROWS ONLY;

SELECT SHORT_NAME, CLUB_NAME, NATIONALITY_NAME,PLAYER_POSITIONS, OVERALL, WAGE_EUR, VALUE_EUR
FROM FIFA_PLAYERS
WHERE FIFA_EDITION = 22
AND OVERALL >= 85
AND WAGE_EUR > 0
AND PLAYER_POSITIONS NOT LIKE '%GK%'
ORDER BY WAGE_EUR ASC
FETCH FIRST 10 ROWS ONLY;

SELECT 
  CASE 
    WHEN PLAYER_POSITIONS LIKE '%GK%' THEN 'Goalkeeper'
    WHEN PLAYER_POSITIONS LIKE '%CB%' OR PLAYER_POSITIONS LIKE '%RB%' OR PLAYER_POSITIONS LIKE '%LB%' THEN 'Defender'
    WHEN PLAYER_POSITIONS LIKE '%CM%' OR PLAYER_POSITIONS LIKE '%CAM%' OR PLAYER_POSITIONS LIKE '%CDM%' THEN 'Midfielder'
    WHEN PLAYER_POSITIONS LIKE '%ST%' OR PLAYER_POSITIONS LIKE '%CF%' OR PLAYER_POSITIONS LIKE '%LW%' OR PLAYER_POSITIONS LIKE '%RW%' THEN 'Forward'
    ELSE 'Other'
  END AS POSITION_GROUP,
  COUNT(*) AS PLAYER_COUNT,
  AVG(OVERALL) AS AVG_OVERALL,
  AVG(PACE) AS AVG_PACE,
  AVG(SHOOTING) AS AVG_SHOOTING,
  AVG(DEFENDING) AS AVG_DEFENDING
FROM FIFA_PLAYERS
WHERE FIFA_EDITION = 22
GROUP BY 
  CASE 
    WHEN PLAYER_POSITIONS LIKE '%GK%' THEN 'Goalkeeper'
    WHEN PLAYER_POSITIONS LIKE '%CB%' OR PLAYER_POSITIONS LIKE '%RB%' OR PLAYER_POSITIONS LIKE '%LB%' THEN 'Defender'
    WHEN PLAYER_POSITIONS LIKE '%CM%' OR PLAYER_POSITIONS LIKE '%CAM%' OR PLAYER_POSITIONS LIKE '%CDM%' THEN 'Midfielder'
    WHEN PLAYER_POSITIONS LIKE '%ST%' OR PLAYER_POSITIONS LIKE '%CF%' OR PLAYER_POSITIONS LIKE '%LW%' OR PLAYER_POSITIONS LIKE '%RW%' THEN 'Forward'
    ELSE 'Other'
  END
ORDER BY AVG_OVERALL DESC;

SELECT CLUB_NAME, COUNT(*) AS SQUAD_SIZE, 
       AVG(OVERALL) AS AVG_RATING,
       MAX(OVERALL) AS BEST_PLAYER_RATING
FROM FIFA_PLAYERS
WHERE FIFA_EDITION = 22
AND CLUB_NAME != 'No Club'
GROUP BY CLUB_NAME
HAVING COUNT(*) >= 11
ORDER BY AVG_RATING DESC
FETCH FIRST 10 ROWS ONLY;

SELECT SHORT_NAME, FIFA_EDITION, OVERALL
FROM FIFA_PLAYERS
WHERE SHORT_NAME IN ('L. Messi', 'Cristiano Ronaldo', 'L. Suárez', 'R. Lewandowski', 'K. De Bruyne')
AND FIFA_EDITION IN (15, 16, 17, 18, 19, 20, 21, 22)
ORDER BY FIFA_EDITION, OVERALL DESC;

SELECT SHORT_NAME, LONG_NAME, FIFA_EDITION, OVERALL
FROM FIFA_PLAYERS
WHERE (SHORT_NAME, LONG_NAME) IN (
    SELECT SHORT_NAME, LONG_NAME
    FROM FIFA_PLAYERS
    GROUP BY SHORT_NAME, LONG_NAME
    ORDER BY AVG(OVERALL) DESC
    FETCH FIRST 5 ROWS ONLY
)
ORDER BY FIFA_EDITION;

SELECT LEAGUE_NAME, AVG(OVERALL) AS AVERAGE_RATING, FIFA_EDITION
FROM FIFA_PLAYERS 
WHERE LEAGUE_NAME IN ('Spain Primera Division', 'English Premier League')
GROUP BY LEAGUE_NAME, FIFA_EDITION
HAVING COUNT(*) >= 100
ORDER BY AVG(OVERALL) DESC;

SELECT 
CASE 
 WHEN PLAYER_POSITIONS LIKE '%GK%' THEN 'Goalkeeper'
    WHEN PLAYER_POSITIONS LIKE '%CB%' OR PLAYER_POSITIONS LIKE '%RB%' OR PLAYER_POSITIONS LIKE '%LB%' THEN 'Defender'
    WHEN PLAYER_POSITIONS LIKE '%CM%' OR PLAYER_POSITIONS LIKE '%CAM%' OR PLAYER_POSITIONS LIKE '%CDM%' THEN 'Midfielder'
    WHEN PLAYER_POSITIONS LIKE '%ST%' OR PLAYER_POSITIONS LIKE '%CF%' OR PLAYER_POSITIONS LIKE '%LW%' OR PLAYER_POSITIONS LIKE '%RW%' THEN 'Forward'
    ELSE 'Other'
  END AS POSITION_GROUP,
  AVG(AGE) AS AVERAGE_AGE, FIFA_EDITION
  FROM FIFA_PLAYERS
  GROUP BY FIFA_EDITION,
  CASE 
 WHEN PLAYER_POSITIONS LIKE '%GK%' THEN 'Goalkeeper'
    WHEN PLAYER_POSITIONS LIKE '%CB%' OR PLAYER_POSITIONS LIKE '%RB%' OR PLAYER_POSITIONS LIKE '%LB%' THEN 'Defender'
    WHEN PLAYER_POSITIONS LIKE '%CM%' OR PLAYER_POSITIONS LIKE '%CAM%' OR PLAYER_POSITIONS LIKE '%CDM%' THEN 'Midfielder'
    WHEN PLAYER_POSITIONS LIKE '%ST%' OR PLAYER_POSITIONS LIKE '%CF%' OR PLAYER_POSITIONS LIKE '%LW%' OR PLAYER_POSITIONS LIKE '%RW%' THEN 'Forward'
    ELSE 'Other'
  END
  ORDER BY FIFA_EDITION, AVG(age) ;
  
  SELECT NATIONALITY_NAME, COUNT(DISTINCT SOFIFA_ID) AS PLAYERS
FROM FIFA_PLAYERS
GROUP BY NATIONALITY_NAME
ORDER BY COUNT(DISTINCT SOFIFA_ID) DESC
FETCH FIRST 10 ROWS ONLY;

SELECT COUNT(
CASE 
WHEN POTENTIAL > OVERALL THEN 1
END) * 100 / COUNT(*) AS POTENTIAL_PERCENTAGE, fifa_edition, AVG(POTENTIAL - OVERALL) AS AVERAGE_DIFFRENCE
FROM FIFA_PLAYERS
GROUP BY FIFA_EDITION
ORDER BY FIFA_EDITION;

SELECT SOFIFA_ID, MIN(FIFA_EDITION) AS FIRST_EDITION, 
MAX(FIFA_EDITION) AS LAST_EDITION
FROM FIFA_PLAYERS
GROUP BY SOFIFA_ID;

SELECT F2.SHORT_NAME, F2.NATIONALITY_NAME,
       F2.OVERALL AS FIRST_RATING,
       F3.OVERALL AS LAST_RATING,
       F3.OVERALL - F2.OVERALL AS RATING_IMPROVEMENT
FROM 
    (SELECT SOFIFA_ID, 
            MIN(FIFA_EDITION) AS FIRST_EDITION, 
            MAX(FIFA_EDITION) AS LAST_EDITION
     FROM FIFA_PLAYERS
     GROUP BY SOFIFA_ID
     HAVING COUNT(DISTINCT FIFA_EDITION) > 1) F1
JOIN FIFA_PLAYERS F2 
    ON F1.SOFIFA_ID = F2.SOFIFA_ID 
    AND F2.FIFA_EDITION = F1.FIRST_EDITION
JOIN FIFA_PLAYERS F3 
    ON F1.SOFIFA_ID = F3.SOFIFA_ID 
    AND F3.FIFA_EDITION = F1.LAST_EDITION
ORDER BY RATING_IMPROVEMENT DESC
FETCH FIRST 10 ROWS ONLY
